apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rpe-expressjs-template App
name: rpe-expressjs-template
home: https://github.com/hmcts/rpe-expressjs-template
version: 0.0.1
dependencies:
  - name: nodejs
    version: 2.3.8
    repository: '@hmctspublic'

