services:
  civilService:
    url: CIVIL_SERVICE_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    clientSecret: IDAM_SECRET
    callbackURL: OAUTH_CLIENT_REDIRECT
  draftStore:
    redis:
      host: REDIS_HOST

port: PORT
appInsights:
  instrumentationKey: APPINSIGHTS_KEY

secrets:
  cmc:
    os-postcode-lookup-api-key: akmD49XpaGfTWz8CD5PUGlhAFw2FBo3a
