services:
  civilService:
    url: CIVIL_SERVICE_URL
  postcodeLookup:
    ordnanceSurveyApiKey: ORDNANCE_SURVEY_API_KEY
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    callbackURL: OAUTH_CLIENT_REDIRECT
  draftStore:
    redis:
      host: REDIS_HOST
      port: REDIS_PORT
      tls: REDIS_TLS
  dmStore:
    microserviceName: MICROSERVICE_NAME
    url: DM_STORE_URL
  serviceAuthProvider:
    url: SERVICE_AUTH_PROVIDER_URL
port: PORT
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
