services:
  civilService:
    url: CIVIL_SERVICE_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    clientSecret: IDAM_SECRET
    callbackURL: OAUTH_CLIENT_REDIRECT
  civil:
     ordnanceSurveyApiKey: ORDNANCE_SURVEY_API_KEY
  draftStore:
    redis:
      host: REDIS_HOST
      port: REDIS_PORT
      tls: REDIS_TLS

port: PORT
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
