services:
  civilService:
    url: CIVIL_SERVICE_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    callbackURL: OAUTH_CLIENT_REDIRECT
    terminateSessionURL: IDAM_END_SESSION_URL
    signOutCallBackURL: IDAM_SIGN_OUT_REDIRECT_URL
  draftStore:
    redis:
      host: REDIS_HOST
      port: REDIS_PORT
      tls: REDIS_TLS
      expireInDays: REDIS_EXPIRE_IN_DAYS
    legacy:
      url: DRAFT_STORE_API_URL
  session:
    redis:
      host: REDIS_HOST
      port: REDIS_PORT
    secureCookie: SECURE_COOKIE
  dmStore:
    microserviceName: MICROSERVICE_NAME
    baseUrl: DOCUMENT_MANAGEMENT_URL
  serviceAuthProvider:
    baseUrl: AUTH_PROVIDER_SERVICE_CLIENT_BASEURL
    serviceAuthTokenGeneratorUrl: SERVICE_AUTH_TOKEN_GENERATOR_URL
  cmc:
    url: OCMC_URL
  pcq:
    url: PCQ_URL
  govPay:
    url: GOVPAY_URL
  carmDate: CARM_DATE
port: PORT
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
