services:
  civilService:
    url: CIVIL_SERVICE_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    callbackURL: OAUTH_CLIENT_REDIRECT
    terminateSessionURL: IDAM_END_SESSION_URL
    signOutCallBackURL: IDAM_SIGN_OUT_REDIRECT_URL
  launchDarkly:
    sdk: LAUNCH_DARKLY_SDK
    env: LAUNCH_DARKLY_ENV
  draftStore:
    redis:
      host: REDIS_HOST
      port: REDIS_PORT
      tls: REDIS_TLS
      expireInDays: REDIS_EXPIRE_IN_DAYS
    legacy:
      url: DRAFT_STORE_API_URL
  session:
    redis:
      host: REDIS_HOST
      port: REDIS_PORT
    secureCookie: SECURE_COOKIE
  dmStore:
    microserviceName: MICROSERVICE_NAME
    baseUrl: DOCUMENT_MANAGEMENT_URL
  serviceAuthProvider:
    baseUrl: AUTH_PROVIDER_SERVICE_CLIENT_BASEURL
    serviceAuthTokenGeneratorUrl: SERVICE_AUTH_TOKEN_GENERATOR_URL
  dynatrace:
    url: DYNATRACE_TAG
  cmc:
    url: OCMC_URL
  pcq:
    url: PCQ_URL
  govPay:
    url: GOVPAY_URL
  civilMoneyClaims:
    telephone: CIVILMONEYCLAIMS_TELEPHONE
    courtEmailId: CIVILMONEYCLAIMS_COURT_EMAIL_ID
    welshspeaker:
      telephone: CIVILMONEYCLAIMS_WELSHSPEAKER_TELEPHONE
  generalApplication:
    url: CIVIL_SERVICE_URL
port: PORT
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
webChat:
  cnbc:
    enabled: WEB_CHAT_CNBC_ENABLED
    uuid: WEB_CHAT_CNBC_UUID
    tenant: WEB_CHAT_CNBC_TENANT
    channel: WEB_CHAT_CNBC_CHANNEL
    channelUuid: WEB_CHAT_CNBC_CHANNEL_UUID
    buttonContainerId: WEB_CHAT_CNBC_BUTTON_ID
  mediation:
    enabled: WEB_CHAT_MEDIATION_ENABLED
    uuid: WEB_CHAT_MEDIATION_UUID
    tenant: WEB_CHAT_MEDIATION_TENANT
    channel: WEB_CHAT_MEDIATION_CHANNEL
    channelUuid: WEB_CHAT_MEDIATION_CHANNEL_UUID
    buttonContainerId: WEB_CHAT_MEDIATION_BUTTON_ID
featureToggles:
  settlementAgreementEnabled: SETTLEMENT_AGREEMENT_ENABLED
cookieMaxAge:
  __name: SESSION_COOKIE_MAX_AGE
  __format: number
