name: Update README Test Documentation Tables

on:
  push:
    branches:
      - master

jobs:
  generate-readme-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Use Node.js 18
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18

      - name: Install dependencies
        env:
          YARN_ENABLE_SCRIPTS: "false"
        run: yarn install --frozen-lockfile

      - name: Regenerate documentation JSON
        run: |
          yarn test:generate:ui-docs

      - name: Update README UI table
        run: yarn test:readme:ui-docs

      - name: Commit and push README updates
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          commit_message: "chore: refresh README test documentation tables"
          branch: master
